name: Build image
on:
  push:
    branches:
      # Matches all branch and tag names that don't contain a slash (/).
      - "*"
    tags:
      # Matches all semantic versioning tags
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Resolve release name
        id: release
        run: |
          RELEASE_NAME=
          GITHUB_REF_STRIPPED=${GITHUB_REF#refs/}
          REF_NAME=${GITHUB_REF_STRIPPED##*/}
          REF_TYPE=${GITHUB_REF_STRIPPED%/*}

          if [[ "$REF_TYPE" == "heads" ]]; then
            if [[ "$REF_NAME" == "master" ]]; then
              RELEASE_NAME="${GITHUB_SHA}"
            else
              RELEASE_NAME="$REF_NAME"
            fi
          elif [[ "$REF_TYPE" == "tags" ]]; then
            RELEASE_NAME="${REF_NAME##v}"
          fi

          echo "Using $RELEASE_NAME as release name."
          echo "::set-output name=name::$RELEASE_NAME"
      # setup docker
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Login to Google Container Registry
      # - name: Login to Google Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: europe-west3-docker.pkg.dev
      #     username: _json_key_base64
      #     password: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64_KEY }}

      # Build docker image
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          # for google add europe-west3-docker.pkg.dev/playground-269614/autoremove-torrents/autoremove-torrents:${{ steps.release.outputs.name }}
          tags: |
            ghcr.io/panzelva/autoremove-torrents:${{ steps.release.outputs.name }}
